# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('clave', models.CharField(max_length=25)),
                ('tipo', models.CharField(max_length=25)),
            ],
        ),
    ]
