# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20181012_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoPractico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.Carrera')),
                ('idUsuario', models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.CASCADE, to='cuentas.Usuarios')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.Materia')),
            ],
        ),
    ]
