# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_trabajopractico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
