# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_auto_20181012_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='carrera',
        ),
        migrations.AlterField(
            model_name='trabajopractico',
            name='carrera',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trabajopractico',
            name='materia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trabajopractico',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
